import { DataTypes, Model } from "sequelize";
import sequelize from "../config/database";

// 📋 Define what a User looks like in TypeScript
interface UserAttributes {
  id?: number;        // Auto-generated by MySQL
  name: string;
  email: string;
  age: number;
  createdAt?: Date;
  updatedAt?: Date;
}

// 🗄️ Create the User model (this becomes a "users" table in MySQL)
class User extends Model<UserAttributes> implements UserAttributes {
  public id!: number;
  public name!: string;
  public email!: string;
  public age!: number;
}

// 🏗️ Define the columns of the "users" table
User.init(
  {
    id: {
      type: DataTypes.INTEGER,     // Number type
      autoIncrement: true,         // 1, 2, 3... auto increases
      primaryKey: true,            // Unique identifier for each row
    },
    name: {
      type: DataTypes.STRING,      // Text type (max 255 chars)
      allowNull: false,            // Cannot be empty — required field
    },
    email: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true,                // No two users can have same email
    },
    age: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
  },
  {
    sequelize,                     // Pass the database connection
    tableName: "users",            // Name of the table in MySQL
    timestamps: true,              // Adds createdAt & updatedAt columns automatically
  }
);

export default User;
